version: '3.7'

services:
  db:
    image: mysql:5.7.25
    command: --default-authentication-plugin=mysql_native_password --explicit-defaults-for-timestamp --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
    volumes:
      - ${PWD}/tmp/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
